# Generated by Django 4.0.1 on 2022-02-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plasmid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sequence', models.CharField(max_length=50000)),
                ('sequenceLength', models.IntegerField()),
                ('backbone', models.CharField(max_length=200)),
                ('features', models.CharField(max_length=1500)),
            ],
        ),
    ]
